import { describe, it, expect } from 'vitest'
import { buildMarkdown } from '../../utils/exportMarkdown'
import type { StrategyDocument } from '../../types'

function createEmptyDoc(businessItem: string): StrategyDocument {
  return {
    id: 'test-id',
    businessItem,
    createdAt: '2026-01-15T00:00:00.000Z',
    updatedAt: '2026-01-15T00:00:00.000Z',
    currentStep: 1,
    frameworks: {},
  }
}

describe('buildMarkdown', () => {
  it('완료된 프레임워크가 없으면 기본 헤더와 사업 아이템만 포함한다', () => {
    const doc = createEmptyDoc('AI 식단관리 앱')
    const md = buildMarkdown(doc)

    expect(md).toContain('AI 식단관리 앱')
    expect(md).toContain('전략 PRD')
    expect(md).toContain('2026-01-15')
    expect(md).toContain('Generated by Strategy Analyzer')
  })

  it('완료된 프레임워크의 이름과 데이터가 포함된다 (리스트 필드)', () => {
    const doc = createEmptyDoc('전기차 충전 사업')
    doc.frameworks = {
      faw: {
        status: 'completed',
        data: {
          facts: ['전기차 보급률 증가', '충전소 부족'],
          assumptions: ['충전 수요 급증 예상'],
          whatIfs: ['무선충전 기술 도입 시'],
        } as unknown as StrategyDocument['frameworks'][string]['data'],
        updatedAt: '2026-01-15T00:00:00.000Z',
      },
    }

    const md = buildMarkdown(doc)

    expect(md).toContain('FAW 분석')
    expect(md).toContain('전기차 보급률 증가')
    expect(md).toContain('충전소 부족')
    expect(md).toContain('충전 수요 급증 예상')
    expect(md).toContain('무선충전 기술 도입 시')
  })

  it('완료된 프레임워크의 테이블 필드가 포함된다', () => {
    const doc = createEmptyDoc('경쟁사 분석 테스트')
    doc.frameworks = {
      competitorAnalysis: {
        status: 'completed',
        data: {
          competitors: [
            ['CompanyA', '기술력', '마케팅 약함', '30%', '기술 리더십'],
            ['CompanyB', '가격 경쟁력', '품질 이슈', '25%', '저가 전략'],
          ],
          differentiators: ['AI 기반 분석', '맞춤형 서비스'],
          gaps: ['중소기업 시장 미개척'],
        } as unknown as StrategyDocument['frameworks'][string]['data'],
        updatedAt: '2026-01-15T00:00:00.000Z',
      },
    }

    const md = buildMarkdown(doc)

    expect(md).toContain('경쟁사 분석')
    expect(md).toContain('경쟁사명')
    expect(md).toContain('CompanyA')
    expect(md).toContain('CompanyB')
    expect(md).toContain('AI 기반 분석')
    // 테이블 형식(| ... |) 확인
    expect(md).toContain('|')
    expect(md).toContain('---')
  })

  it('텍스트 필드가 포함된다', () => {
    const doc = createEmptyDoc('STP 테스트')
    doc.frameworks = {
      stp: {
        status: 'completed',
        data: {
          segmentation: ['20대 직장인', '30대 가족'],
          targeting: '20대 직장인 세그먼트',
          positioning: '편리한 일상 건강관리 파트너',
        } as unknown as StrategyDocument['frameworks'][string]['data'],
        updatedAt: '2026-01-15T00:00:00.000Z',
      },
    }

    const md = buildMarkdown(doc)

    expect(md).toContain('STP')
    expect(md).toContain('20대 직장인 세그먼트')
    expect(md).toContain('편리한 일상 건강관리 파트너')
  })

  it('empty 상태의 프레임워크는 출력에 포함되지 않는다', () => {
    const doc = createEmptyDoc('필터 테스트')
    doc.frameworks = {
      faw: { status: 'empty', data: null, updatedAt: null },
      pest: { status: 'generating', data: null, updatedAt: null },
      swot: { status: 'error', data: null, updatedAt: null, error: '오류' },
    }

    const md = buildMarkdown(doc)

    expect(md).not.toContain('FAW 분석')
    expect(md).not.toContain('PEST 분석')
    expect(md).not.toContain('SWOT 분석')
  })
})
