/**
 * Obsidian 호환 Markdown 내보내기
 */
import type { StrategyDocument, FrameworkDefinition } from '../types'
import { FRAMEWORKS } from '../data/frameworkDefinitions'
import { SECTIONS } from '../data/sectionDefinitions'

function listToMd(items: string[]): string {
  if (!items?.length) return '_데이터 없음_\n'
  return items.map((item) => `- ${item}`).join('\n') + '\n'
}

function tableToMd(columns: string[], rows: unknown[]): string {
  if (!rows?.length) return '_데이터 없음_\n'
  const header = '| ' + columns.join(' | ') + ' |'
  const separator = '| ' + columns.map(() => '---').join(' | ') + ' |'
  const body = rows
    .map((row) => {
      const cells = Array.isArray(row) ? row : Object.values(row as Record<string, unknown>)
      return '| ' + cells.join(' | ') + ' |'
    })
    .join('\n')
  return header + '\n' + separator + '\n' + body + '\n'
}

function frameworkToMd(id: string, data: Record<string, unknown>): string {
  const fw: FrameworkDefinition | undefined = FRAMEWORKS[id]
  if (!fw || !data) return ''

  let md = `### ${fw.name}\n`
  md += `> [!info] ${fw.fullName}\n> ${fw.description}\n\n`

  for (const [key, fieldDef] of Object.entries(fw.fields)) {
    const value = data[key]
    if (value === undefined || value === null) continue

    if (fieldDef.type === 'list') {
      md += `**${fieldDef.label}**\n${listToMd(value as string[])}\n`
    } else if (fieldDef.type === 'text' || fieldDef.type === 'select') {
      md += `**${fieldDef.label}**: ${value}\n\n`
    } else if (fieldDef.type === 'table') {
      md += `**${fieldDef.label}**\n${tableToMd(fieldDef.columns, value as unknown[])}\n`
    } else if (fieldDef.type === 'object') {
      md += `**${fieldDef.label}**\n`
      if (typeof value === 'object' && value !== null) {
        for (const [subKey, subVal] of Object.entries(value as Record<string, unknown>)) {
          const subLabel = fieldDef.subfields?.[subKey] || subKey
          md += `- **${subLabel}**: ${typeof subVal === 'object' ? JSON.stringify(subVal) : subVal}\n`
        }
      }
      md += '\n'
    }
  }

  return md
}

function buildMarkdown(state: StrategyDocument): string {
  const date = new Date(state.createdAt).toISOString().split('T')[0]

  let md = `---
title: "${state.businessItem} - 전략 PRD"
date: ${date}
tags: [전략분석, PRD, ${state.businessItem}]
---

# ${state.businessItem} — 전략 PRD

> [!abstract] 자동 생성 전략 문서
> 전략분석기(Strategy Analyzer)로 생성됨 | ${date}

---

`

  for (const section of SECTIONS) {
    md += `## ${section.number}. ${section.title}\n`
    md += `*${section.subtitle} — ${section.description}*\n\n`

    for (const fId of section.frameworks) {
      const fState = state.frameworks[fId]
      if (fState?.status === 'completed' && fState.data) {
        md += frameworkToMd(fId, fState.data as unknown as Record<string, unknown>)
        md += '---\n\n'
      }
    }
  }

  md += `\n---\n*Generated by Strategy Analyzer*\n`
  return md
}

export function exportMarkdown(state: StrategyDocument): void {
  const md = buildMarkdown(state)
  const blob = new Blob([md], { type: 'text/markdown;charset=utf-8' })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = `${state.businessItem}_전략PRD_${new Date().toISOString().split('T')[0]}.md`
  document.body.appendChild(a)
  a.click()
  document.body.removeChild(a)
  URL.revokeObjectURL(url)
}

/** 마크다운 문자열 생성 (미리보기용) */
export { buildMarkdown }
